//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fibresInTexilesMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        public string Overview { get; set; }
        public int FiberId { get; set; }
    
        public virtual fibre fibre { get; set; }
    }
}
